// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proto/simple_calc.proto

package grpc_calc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalcPerformerClient is the client API for CalcPerformer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalcPerformerClient interface {
	Calculate(ctx context.Context, in *Operation, opts ...grpc.CallOption) (*OperationResult, error)
}

type calcPerformerClient struct {
	cc grpc.ClientConnInterface
}

func NewCalcPerformerClient(cc grpc.ClientConnInterface) CalcPerformerClient {
	return &calcPerformerClient{cc}
}

func (c *calcPerformerClient) Calculate(ctx context.Context, in *Operation, opts ...grpc.CallOption) (*OperationResult, error) {
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, "/grpc_calc.CalcPerformer/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalcPerformerServer is the server API for CalcPerformer service.
// All implementations must embed UnimplementedCalcPerformerServer
// for forward compatibility
type CalcPerformerServer interface {
	Calculate(context.Context, *Operation) (*OperationResult, error)
	mustEmbedUnimplementedCalcPerformerServer()
}

// UnimplementedCalcPerformerServer must be embedded to have forward compatible implementations.
type UnimplementedCalcPerformerServer struct {
}

func (UnimplementedCalcPerformerServer) Calculate(context.Context, *Operation) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}
func (UnimplementedCalcPerformerServer) mustEmbedUnimplementedCalcPerformerServer() {}

// UnsafeCalcPerformerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalcPerformerServer will
// result in compilation errors.
type UnsafeCalcPerformerServer interface {
	mustEmbedUnimplementedCalcPerformerServer()
}

func RegisterCalcPerformerServer(s grpc.ServiceRegistrar, srv CalcPerformerServer) {
	s.RegisterService(&CalcPerformer_ServiceDesc, srv)
}

func _CalcPerformer_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Operation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcPerformerServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_calc.CalcPerformer/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcPerformerServer).Calculate(ctx, req.(*Operation))
	}
	return interceptor(ctx, in, info, handler)
}

// CalcPerformer_ServiceDesc is the grpc.ServiceDesc for CalcPerformer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalcPerformer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_calc.CalcPerformer",
	HandlerType: (*CalcPerformerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _CalcPerformer_Calculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/simple_calc.proto",
}
